### ISSUE TITLE
Create feature styler

### ISSUE THREAD

**Issue by joergreichert** [Mapzone/mapzone#14]
# subtasks
- [ ] Polymap4/polymap4-p4#14
- [X] Dialog für Angabe der einfachen Style-Attribute wie Font, Hintergrundfarbe (optional), Größe, Umrandung usw.
- [X] Dialog-Infrastruktur für Auswahl eines (optionalen) Symbols (analog zu Color-Dialog, erstmal nur die Eclipse Icons aus der SharedLibrary angezeigt).
- [x] Icon Bibliotheken einbinden (als zip in Plugin legen und dann zur Laufzeit auspacken?)
  - [x] [Simpleicon Places](http://www.flaticon.com/packs/simpleicon-places/) aus [simpleicon.com/](http://simpleicon.com/)
  - [x] [Pins of maps](http://www.flaticon.com/packs/pins-of-maps/) aus [freepik.com](http://freepik.com/)
  - [x] [MapBox POI Icon Set](https://www.mapbox.com/maki/)
- [ ] Icon Auswahl anzeigen
  - [x] Auswahl-Dialog
  - [ ] Upload image file (+ persistieren)
  - [ ] Upload / reference image file from remote URL
- [ ] Style-List
  - [ ] View mit Label (evt. Preview, z.B. Icon) + Selection
  - [x] New Style Action
  - [ ] Load Style Action
  - [ ] Copy Style Action
  - [x] Delete Style Action
- [ ] Style-Editor mit Preview (aktuell Stand: Pipeline wird verwendet, es kommt aber nur eine schwarzes Bild raus)
- [ ] Neuen Style aus bestehenden Style ableiten / kopieren
- [ ] Style Parametrisierung, unabhängig von Layer, d.h. Parameter müssen später in der Layer-spezifischen Konfiguration an FeatureType-Attribute gebunden werden können
- [ ] View für Style Selektion pro aktiven Layer (Auswahl von Style aus Style Bibliothek, Wechseln in den Layer-unabhängigen Styler-Editor (und zurück)
- [x] SLD aus Dialog-Angaben aufbauen, z.B. mittels `org.geotools.styling.builder.StyledLayerDescriptorBuilder` oder `org.geotools.styling.StyleBuilder`
- [ ] SLD serialisieren und deserialisieren können
  - [x] in JUnit-Test
  - [ ] in Persistenz
- [ ] Filter bauen
- [ ] Rule bauen
  - [ ] Prüfen, ob Rules in SLD hierarchisch/geschachtelt aufgebaut werden können, und wenn nicht, was zu tun ist, um in einem nachgelagerten Schritt, komplementäre Regeln an den jeweils anderen Regeln automatisch anzuheften, so dass sich die Regeln jeweils ausschließen
- [ ] Hierarchische Styles
  - [ ] siehe Style aus bestehenden Style ableiten - Fields mit Checkbox, die signalisieren, dass Werte aus referenzierten Style überschrieben werden sollen, wenn angehakt, ansonsten vom referenzierten Style übernommen werden sollen
- [ ] Klären, wie Images in SLD referenziert werden können (müssen die entpackt im Workspace liegen oder können durch eine Dummy-URL aus dem Speicher referenziert werden (beim SLD Export muss natürlich trotzdem das Image mit exportiert werden können)?)
- [ ] Prüfen, ob marker fill nur für well known names (wie circle, star, ...) gilt oder auch für selbst gelieferte Images (Unterscheidung well-known-names und Icons für Nutzer nicht intuitiv, von daher könnte man dann das fill auch für SVGs anwenden, um diese dem Fill entsprechend einzufärben)
- [ ] Extension Points
  - [ ] Value Objects und toSLD-Methoden so aufteilen, dass die einzelnen Aspekte, wie eine SLD aufzubauen ist auch in der UI frei kombinierbar sind, und auch Erweiterungen für bestimmte Aspekte geliefert werden können, die sich dann dynamisch in die UI einbetten und sich auch in die SLD-Serialisierung/Deserialisierungs-Prozesse einfügen (z.B. spezifisch Label, Rules, Filter, Point, Polyline/LineString, Polygon)
- [ ] Complex Styles
  - [ ] Durchstich Maßstabs-abhängiges Styling (Icon-Auswahl, Anpassen der Marker-Größe)
    - [ ] UI, um bestimmten Style an bestimmten Maßstabswert / Maßstabswertebereich zu binden
  - [ ] Durchstich Kategorien
  - [ ] UI, um bestimmten Style an bestimmten FeatureType-Attributwert / FeatureType-Wertebereich zu binden
  - [ ] Kombination von Complex Styles (ggf. Reihenfolge-abhängig, z.B. mehrere Kategorien, Kategorien und Maßstab, usw.)
# Requirements
- non functional requirements
  - simple / intuitive to use
    - e.g. hiding extra options in expert mode and using common default values for them?
    - offering only small, medium, large for size instead of concrete pixel values
    - offering predefined templates / style library
  - data to configure should be conform to SLD standard
  - WYSIWYG: preview of changes made in style editor in map
  - configuration
    - general
      - label
        - which data field to use for label, if any
      - font (font, size, color)
      - offset (from marker, from line, from polygon)
      - allow label overlap
    - line color (via color picker, RGB color)
    - line width (in pixel)
    - line opacity (0..1)
    - line border (see general)
  - point specific
    - marker color
    - marker symbol (image or type like ellipse)
    - marker opacity (0..1)
    - marker size (in pixel)
    - marker border (see general)
  - line specific
    - dash array (e.g. dotted line)
    - smooth factor (simplification of line when zooming out)
  - polygon specific
    - fill color
    - fill pattern (e.g. filling up space of polygon with repeating a symbol)
    - fill gradients (or is this done by rasters?)
    - polygon border (see general)
  - raster specific
    - defining color map entries with color and quantity
    - channel selection

[SLD cookbook](http://docs.geoserver.org/stable/en/user/styling/sld-cookbook/index.html)
- actions
  - copy existing style to be used as template for defining a new style
  - inherit attributes from another style (attribute value = inherited)
  - generate default style (e.g. automatically select properties of feature like name to be used as label)
  - editing in SLD editor (or CSS Editor)
  - upload custom marker images
  - rule based styling, e.g. when feature property a is b then use fill color c
- entry points
  - selecting/applying styles at features import (initially use default style)
  - changing style 
    - for a layer (style theme)
    - for a single feature in a layer

_Screenshots from CartoDB:_

geometry type selection:
![cartodb geometry type selection](https://cloud.githubusercontent.com/assets/994131/10019594/9efb60ec-613e-11e5-87c9-189925296cf6.png)

Point:
![cartodb point style editor 1](https://cloud.githubusercontent.com/assets/994131/10019602/9f22c682-613e-11e5-8472-0ac852409bfa.png)
![cartodb point style editor 2](https://cloud.githubusercontent.com/assets/994131/10019596/9efe3bdc-613e-11e5-9839-2526ddae1e9d.png)

Line:
![cartodb line style editor](https://cloud.githubusercontent.com/assets/994131/10019590/9ee06990-613e-11e5-93b3-abb74af7e0b1.png)

Polygon:
![cartodb polygon style editor](https://cloud.githubusercontent.com/assets/994131/10019588/9edfba86-613e-11e5-8aa0-5f75b8053ad0.png)
![cartodb polygon style editor 1](https://cloud.githubusercontent.com/assets/994131/10019589/9ee01166-613e-11e5-87b4-fecdf102e649.png)
![cartodb polygon style editor 2](https://cloud.githubusercontent.com/assets/994131/10019591/9ee2b7a4-613e-11e5-9aaf-4915352aba69.png)

Symbol selection:
![cartodb icon selection](https://cloud.githubusercontent.com/assets/994131/10019595/9efdf8a2-613e-11e5-9e8d-221721e8f509.png)

Css-Editor
![cartodb css editor](https://cloud.githubusercontent.com/assets/994131/10019598/9effb3cc-613e-11e5-82ed-d55711f56b4a.png)

_Screenshots from umap:_
![umap line css editor](https://cloud.githubusercontent.com/assets/994131/10019587/9edf9772-613e-11e5-8243-5d6f4d5abdf0.png)
![umap point css editor](https://cloud.githubusercontent.com/assets/994131/10019592/9ee366d6-613e-11e5-98cb-500b20318cd7.png)

_Screenshots from GeoServer:_
![data_style_editor](https://cloud.githubusercontent.com/assets/994131/10019593/9efb07e6-613e-11e5-880b-fd5dde87b460.png)

_Screenshots from MapBox:_

![mapbox style editor 1](https://cloud.githubusercontent.com/assets/994131/10019599/9f1e0714-613e-11e5-94a0-11cf1da489e8.png)
![mapbox style editor 2](https://cloud.githubusercontent.com/assets/994131/10019597/9efe7f52-613e-11e5-966c-417b3c61c010.png)
![mapbox style editor 3](https://cloud.githubusercontent.com/assets/994131/10019601/9f225cd8-613e-11e5-8c7b-8d399933c6c5.png)
![mapbox style editor 4](https://cloud.githubusercontent.com/assets/994131/10019600/9f1e728a-613e-11e5-9627-b55852348122.png)

Other alternatives:
- [uDig Style editor](http://udig.github.io/docs/user/getting_started/walkthrough1/ThemedData.html#style-editor)
- [GeoServer](http://docs.geoserver.org/latest/en/user/webadmin/data/styles.html)
- [GeoMajas Style Editor](http://www.geomajas.org/sld-editor)
- [OpenJUMP](http://openjump.org/)
- [AtlasStyler](http://giswiki.org/wiki/AtlasStyler)
- [QGis](http://planet.qgis.org/planet/tag/sld/)
