### ISSUE TITLE
Projects and Layers

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone#2]
For Arena #1 we need at least:

  - Model of projects and layers
  - connection to data/feature sources (resolver)
  - UI to manage layers of a project

Depends on:

- [x] Polymap4/polymap4-core#3 
- [x] Polymap4/polymap4-core#5
- [x] Polymap4/polymap4-core#6
- [x] Polymap4/polymap4-core#7
- [x] Polymap4/polymap4-core#9
- [ ] Polymap4/polymap4-p4#110 (working on it...)
