### ISSUE TITLE
Dashboard landing page

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone#27]
Die landing page ist der erste Eindruck, den ein Interessent von mapzone bekommt, wenn er **das erste Mal** bei uns aufschlägt oder von eienr **erstenen Referenz/Werbung/Erwähnung**. Das ist etwas anderes als die homepage eines Nutzers. Die homepage eines Nutzers ist sein dashboard.

Die landing page hat folgende **Aufgaben**:
- ermöglicht dem Leser möglichst leicht zu erkennen ob mapzone relevant für ihn ist, deshalb...
- ... vermittelt sie eine Idee von den Angebotenem Service, und...
- ... gibt möglichst einfache, direkte Wege, um sich weiter zu informieren

Diese Schritte müssen eventuell in 1-2 **Iterationen** laufen, von allgemeinen zum speziellen/spezifischen Informationen. Somit ermöglichen wir dem Interessenten, die für ihn wichtigen Informationen selbst auszuwählen und damit die Relevanz der Informationen selbst zu bestimmen (zu steigern).

**Lösungsansatz**
- Titel/Blickfang: **mapzone**
- danach ein 2-3 Sätze zum Gegenstand (nicht nur ein typischer claim)
- dabei: **Start your first project**

_Mit mapzone können Sie ihre fachspezifischen Daten ... Der Dienst hilft Ihnen beim Erfassen, Bearbeiten, und Publizieren im Web._

**Todo:**
- [x] Layout: Header mit Titel und Erklärung
- [x] Startknopf: erstes Projekt anlegen
- [x] einzelne "Sections" darunter
- [x] Desktop, Tablet, Phone
- [x] richtige Maps als Hintergrund für Header und/oder Sections
- [x] notwendige Links (Impressum, Legal, etc.)
