### ISSUE TITLE
Material Design for Batik

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone#3]
Implement [Material Design](http://www.google.com/design/spec) for [Batik](Polymap4/polymap4-rhei/plugins/org.polymap.rhei.batik).

Tasks:
- [ ] Polymap4/polymap4-rhei#6
- [ ] Polymap4/polymap4-rhei#7
- [x] Polymap4/polymap4-rhei#8
- [x] Polymap4/polymap4-rhei#12
- [x] Polymap4/polymap4-rhei#15
- [x] Polymap4/polymap4-rhei#31
- [ ] add more tickets
