### ISSUE TITLE
[GeoServer] WMS

### ISSUE THREAD

**Issue by joergreichert** [Mapzone/mapzone#4]
Make GeoServer generally available in mapzone. Expose WMS with proper name and styles.

Depends on:
- [x] Basic GeoServer integration: Polymap4/polymap4-core#2
- [ ] Namespace: Polymap4/polymap4-core#16
- [x] Layer styles: Polymap4/polymap4-core#59
- [x] Cascaded WMS layer: Polymap4/polymap4-core#61
- [x] Reload on change: Polymap4/polymap4-core#15
- [ ] Multi layer request: https://github.com/Polymap4/polymap4-p4/pull/100

TODO:
- [x] auth token
- [ ] doc: ProjectInfoPanel
- [ ] for GeoServer we may need to cache IPs as subsequent request may miss the token
- [x] migrate org.polymap.service.geoserver to use GeoTools 13 and GeoServer 2.7.0
- [x] get Spring based GeoServer to run in Equinox
  *\* http://www.eclipse.org/gemini/blueprint/documentation/reference/1.0.2.RELEASE/html/index.html
  *\* https://access.redhat.com/documentation/en-US/Red_Hat_JBoss_Fuse/6.1/html/Migration_Guide/ESBMigrationIntro-SpringDM.html
  *\* http://blog.osgi.org/2014/09/how-should-i-use-guicespringblueprint.html 
- [x] dependency only to org.polymap.core (use GeoTools from core.data) 
- [ ] ensure that GeoServer uses our context
