### ISSUE TITLE
[Arena] Go live

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone#56]
#### P4/Arena
- [ ] #2
- [ ] #17
- [ ] #33 (?)
- [ ] #40
- [ ] Graph Beta: #57 
- [ ] ProjectMapPanel: handle project/layer extent
- [x] FeatureTable: many features
- [ ] ResourceInfoPanel: Polymap4/polymap4-p4#61
- [ ] LayerInfoPanel: Polymap4/polymap4-p4#76
- [ ] Delete layer: Polymap4/polymap4-p4#93
- [ ] Polymap4/polymap4-p4#9
- [x] CSV:CRS Selector Polymap4/polymap4-p4#33
- [x] WMS: Preview Polymap4/polymap4-p4#54
- [ ] Import 100.000 only: Polymap4/polymap4-p4#98
#### OpenLayers
- [x] Polymap4/polymap4-rap#21
