### ISSUE TITLE
[Controller] Plugin catalog

### ISSUE THREAD

**Issue by fb71** [Mapzone/mapzone#97]
Generic catalog framework and plugin catalog.

  - [x] basic generic, extendible model
  - [x] WebDAV API (#96)
  - [x] generic client (io.mapzone.ide.apiclient)
  - [x] use for plugin catalog

## Plugins browser / Detail panel
  
  - [x] list: name, (generic) icon, description, fee/free
  - [x] detail: fields (markdown?)
  - [x] properly handle empty fields and URLs in markdown
  - [ ] reload browser (detail panel) after entity changed event

## "My Plugins" Browser

  - [x] icon reflecting install state
  - [x] form modify (?)
  - [x] delete Plugin -> Revoke

## TODO

  - [ ] doUninstall()
  - [ ] check project admin permissions before install
  - [ ] display installed/available version
  - [ ] "..." in accordion dashboard
  - [x] mapzone.io frontpage
  - [x] make an OSM plugin to see if everything is going well
  - [x] Dashlet priority on DashboardPanel
  - [ ] Dashlet height on DashboardPanel (?)
  - [x] subsequently open projects

## We might use the base WebCat for:

  - Plugin catalog
  - Style/Symbols catalog
  - Data/Service catalog (?)

**Comment by fb71** [comment]
We have been using this for quite some time. Some points are still "to do", however I'm gone close this for now. We will come back for a next round of catalog development when there is demand and we have accumulated more experiences.
